# action.yml
name: "Containerised Python 3"
description: "Run a command in a Python 3 container."
inputs:
  command:
    description: "Run python tests."
    required: true
    default: "pytest tests"
runs:
  using: "docker"
  image: "Dockerfile"
  pre-entrypoint: "install.sh"
  entrypoint: "entrypoint.sh"
  args:
    - ${{ inputs.command }}

# # action.yml
# name: "Containerised Python"
# description: "Greet someone and record the time"
# inputs:
#   who-to-greet: # id of input
#     description: "Who to greet"
#     required: true
#     default: "World"
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
    
# runs:
#   using: "node12"
#   main: "index.js"
