# action.yml
name: "Containerised Python 3.x"
description: "Run a Python 3.x script in a Ubuntu 18.04 (Bionic) container."
inputs:
  python-version: # id of input
    description: "Python version to install."
    required: true
    default: "3.7.8"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-version }}

# # action.yml
# name: "Containerised Python"
# description: "Greet someone and record the time"
# inputs:
#   who-to-greet: # id of input
#     description: "Who to greet"
#     required: true
#     default: "World"
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
    
# runs:
#   using: "node12"
#   main: "index.js"
