# action.yml
name: "Containerised Python 3.x"
description: "Run a Python 3.x script in a Ubuntu 18.04 (Bionic) container."
inputs:
  python-version: # id of input
    description: "Python version to install."
    required: true
    default: "3.7.8"
runs:
  using: "docker"
  image: "docker://python:${{ inputs.python-version }}"
  args:
    - ${{ inputs.python-version }}
